<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitContactsInteraction
{
    public static $prefixLengthsPsr4 = array (
        'O' => 
        array (
            'OCA\\ContactsInteraction\\' => 24,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'OCA\\ContactsInteraction\\' => 
        array (
            0 => __DIR__ . '/..' . '/../lib',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitContactsInteraction::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitContactsInteraction::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
